[workspace]
members = [
    "orbtk",
    "api",
    "localization",
    "proc_macros",
    "shell",
    "theme_default",
    "theme_fluent",
    "theme_redox",
    "theming",
    "tree",
    "utils",
    "widgets"
]