[package]
name = "orbtk_orbclient"
version = "0.3.1-alpha4"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[lib]
doctest = false

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"
console_error_panic_hook = "0.1.6"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = { version = "0.23",  default-features = false, features = ["ico"] }

# orbclient
orbclient = { git = "https://gitlab.redox-os.org/redox-os/orbclient.git", branch = "master", optional = true }

[target.'cfg(all(not(target_os = "redox"), not(target_arch = "wasm32")))'.dependencies]
sdl2 = { version = "0.34", features = ["bundled", "static-link", "raw-window-handle"], optional = true }

[dependencies]
lazy_static = "1.4.0"
raw-window-handle = "0.3"

# orbtk
orbtk_tinyskia = { path = "../orbtk_tinyskia", version = "0.3.1-alpha4", default-features = false }
orbtk_utils = { path = "../utils", version = "0.3.1-alpha4" }

[features]
default = ["orbclient", "sdl2"]
log = []